name: windowmasker_2_5_0
owner: yating-l
description: Identify repetitive regions using WindowMasker
type: unrestricted
homepage_url: https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/app/winmasker/
categories: [Sequence Analysis]
long_description: |
  WindowMasker identifies repetitive sequences and low complexity regions within a
  genome assembly. WindowMasker works in two stages. In stage 1, mkcount produces a
  unit counts file for a genome assembly. In stage 2, ustat uses the unit counts file
  to mask repeats in the genome assembly. See Morgulis A, 2006 (PMID: 16287941) for details.
